"""Portable host adapters and contract-test implementations."""

from mailhub.hosts.http import (
    HttpAgentMemoryAdapter,
    HttpAiExecutionAdapter,
    HttpApprovalAdapter,
    HttpAuditAdapter,
    HttpCredentialBrokerAdapter,
    HttpEventPublisherAdapter,
    HttpHostActionAdapter,
    HttpHostIdentityAdapter,
    HttpKillSwitchAdapter,
    HttpKnowledgeLifecycleAdapter,
    HttpKnowledgeSafetyAdapter,
    HttpKnowledgeSink,
    HttpNotificationAdapter,
    HttpOAuthCallbackAdapter,
    HttpOAuthStateStore,
    HttpObjectStoreAdapter,
    HttpProviderNotificationVerifierAdapter,
    HttpProviderSubscriptionAdapter,
    HttpQuotaAdapter,
    HttpSenderInterlockAdapter,
    HttpTelemetryAdapter,
)
from mailhub.hosts.inmemory import (
    RecordingAgentMemory,
    RecordingEventPublisher,
    RecordingHostActionAdapter,
    RecordingKillSwitch,
    RecordingKnowledgeLifecycle,
    RecordingKnowledgeSafetyAdapter,
    RecordingKnowledgeSink,
)
from mailhub.hosts.legacy import (
    AeroLinkDeliverySnapshot,
    AeroLinkMailAdapter,
    ApprovedCampaignSnapshot,
    CAACTRAININGMailAdapter,
    LegacyDeliveryKind,
    project_delivery_result,
)
from mailhub.hosts.migration import (
    LegacyReference,
    LegacyReferenceMap,
    MigrationAuditEvent,
    MigrationBatch,
    MigrationController,
    MigrationFeatureFlags,
    MigrationPhase,
    NoDualSenderInterlock,
    SenderInterlockPort,
    ShadowComparison,
    compare_shadow,
)
from mailhub.hosts.postgres import PostgresSenderInterlockAdapter
from mailhub.hosts.postgres_quota import PostgresQuotaPort

__all__ = [
    "HttpHostActionAdapter",
    "HttpAgentMemoryAdapter",
    "HttpHostIdentityAdapter",
    "HttpCredentialBrokerAdapter",
    "HttpEventPublisherAdapter",
    "HttpApprovalAdapter",
    "HttpObjectStoreAdapter",
    "HttpAiExecutionAdapter",
    "HttpAuditAdapter",
    "HttpNotificationAdapter",
    "HttpOAuthCallbackAdapter",
    "HttpOAuthStateStore",
    "HttpProviderSubscriptionAdapter",
    "HttpProviderNotificationVerifierAdapter",
    "HttpTelemetryAdapter",
    "HttpQuotaAdapter",
    "HttpSenderInterlockAdapter",
    "PostgresSenderInterlockAdapter",
    "PostgresQuotaPort",
    "HttpKnowledgeSink",
    "HttpKnowledgeLifecycleAdapter",
    "HttpKnowledgeSafetyAdapter",
    "HttpKillSwitchAdapter",
    "AeroLinkDeliverySnapshot",
    "AeroLinkMailAdapter",
    "ApprovedCampaignSnapshot",
    "CAACTRAININGMailAdapter",
    "LegacyReference",
    "LegacyReferenceMap",
    "LegacyDeliveryKind",
    "MigrationBatch",
    "MigrationAuditEvent",
    "MigrationController",
    "MigrationFeatureFlags",
    "MigrationPhase",
    "NoDualSenderInterlock",
    "SenderInterlockPort",
    "RecordingHostActionAdapter",
    "RecordingKillSwitch",
    "RecordingAgentMemory",
    "RecordingKnowledgeLifecycle",
    "RecordingKnowledgeSafetyAdapter",
    "RecordingKnowledgeSink",
    "RecordingEventPublisher",
    "ShadowComparison",
    "compare_shadow",
    "project_delivery_result",
]
